#!/bin/bash

echo "🔧 Configuring Supabase Edge Function Environment Variables"
echo "════════════════════════════════════════════════════════════"

PROJECT_REF="latxadqrvrrrcvkktrog"

echo "📋 Unipile API Configuration:"
echo "   API Key: TE3VJJ3-N3E63ND-MWXM462-RBPCWYQ"
echo "   Base URL: https://api6.unipile.com:13443/api/v1"
echo ""

echo "🚀 To configure the Edge Function environment variables:"
echo ""
echo "1. Go to Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/${PROJECT_REF}/functions"
echo ""
echo "2. Click on 'linkedin-import' function"
echo ""
echo "3. Navigate to 'Environment Variables' section"
echo ""
echo "4. Add these environment variables:"
echo "   ┌─────────────────┬─────────────────────────────────────────┐"
echo "   │ Variable Name   │ Value                                   │"
echo "   ├─────────────────┼─────────────────────────────────────────┤"
echo "   │ UNIPILE_API_KEY │ TE3VJJ3-N3E63ND-MWXM462-RBPCWYQ        │"
echo "   │ UNIPILE_URL     │ https://api6.unipile.com:13443/api/v1   │"
echo "   └─────────────────┴─────────────────────────────────────────┘"
echo ""
echo "5. Click 'Save' to apply the changes"
echo ""
echo "🧪 Test the function after configuration:"
echo "   https://${PROJECT_REF}.supabase.co/functions/v1/linkedin-import"
echo ""
echo "🎉 Your server-side LinkedIn import will be ready to use!"